#Generated by Fabric Compiler ( version 2020.3-Lite <build 71107> ) at Tue Oct 25 17:32:39 2022

report_power 
gen_netlist 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
pnr 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
pnr 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
add_design D:/panguprj/tinydram/ipcore/pll/pll.idf
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
dev_map 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
add_design "D:/panguprj/tinydram/source/top.v"
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
report_power 
gen_netlist 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
remove_design -verilog "D:/panguprj/tinydram/source/top.v"
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module tinyriscv_soc_top
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
add_design "D:/FPGA_LAB_pangomicro/tinyriscv/FPGA_Competition-RISC-V_Processor-in-PGL22G-main/source/perips/spi.v"
add_design "D:/FPGA_LAB_pangomicro/tinyriscv/FPGA_Competition-RISC-V_Processor-in-PGL22G-main/source/perips/spi.v"
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module tinyriscv_soc_top
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module jtag_top
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module jtag_top
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module jtag_top
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_core
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_core
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_core
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_core
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
add_fic "D:/FPGA_LAB_pangomicro/tinyriscv/FPGA_Competition-RISC-V_Processor-in-PGL22G-main/synthesize/tinyriscv_soc_top_syn.fic"
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
dev_map 
pnr 
report_timing 
gen_bit_stream 
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module gen_rst_def_dff
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
dev_map 
dev_map 
pnr 
report_timing 
gen_bit_stream 
dev_map 
dev_map 
dev_map 
dev_map 
pnr 
report_timing 
gen_bit_stream 
dev_map 
pnr 
report_timing 
gen_bit_stream 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
dev_map 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
remove_fic -force"D:/FPGA_LAB_pangomicro/tinyriscv/FPGA_Competition-RISC-V_Processor-in-PGL22G-main/synthesize/tinyriscv_soc_top_syn.fic"
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
remove_design -force D:/FPGA_LAB_pangomicro/tinyriscv/FPGA_Competition-RISC-V_Processor-in-PGL22G-main/ipcore/ram1/ram1.idf
add_design D:/FPGA_LAB_pangomicro/tinyriscv/FPGA_Competition-RISC-V_Processor-in-PGL22G-main/ipcore/ram1/ram1.idf
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -system_verilog -top_module tinyriscv_soc_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
