


RISCV_PREFIX   ?= riscv32-unknown-elf-
RISCV_GCC      ?= $(RISCV_PREFIX)gcc
RISCV_OBJDUMP  ?= $(RISCV_PREFIX)objdump
RISCV_OBJCOPY  ?= $(RISCV_PREFIX)objcopy
RISCV_GCC_OPTS ?= -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles

COMPILE_TARGET=\
    $$(RISCV_GCC) $(1) $$(RISCV_GCC_OPTS) \
        -I$(ROOTDIR)/riscv-test-env/ \
        -I$(ROOTDIR)/riscv-test-env/p/ \
        -I$(TARGETDIR)/$(RISCV_TARGET)/ \
        -T$(ROOTDIR)/riscv-test-env/p/link.ld $$(<) \
        -o $$(@); \
    $$(RISCV_OBJDUMP) -D $$(@) > $$(@).objdump; \
    $$(RISCV_OBJCOPY) -O binary $$(@)  $$(@).bin
